# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

set external_functions
newsheet "Sheet1"
movetosheet "Sheet1"
let A0 = 5
let A1 = 4
let A2 = 6
goto A0
