# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

set external_functions
newsheet "Sheet1"
movetosheet "Sheet1"
label A0 = "hi"
goto A1
